Finished Test Exercises.
GitaVazdike/codelex-exercises pull request #12
Opened 2022-04-01 17:58 UTC by GitaVazdike

2022-04-02 10:03 UTC, janistumpelis requested changes
Nu pirmais uzdevums ir tīri ok, pārējais gan jāpalabo un jāpabeidz 👍

2022-04-02 10:03 UTC, janistumpelis commented on src/main/java/io/codelex/javaadvancedtest/exercise1/Card.java
> +    private double balance;
Naudai vajadzētu izmantot BigDecimal

2022-04-02 10:03 UTC, janistumpelis commented on src/main/java/io/codelex/javaadvancedtest/exercise1/CreditCard.java
> +    public void takeMoney(double moneyAmount) throws NotEnoughFundsException {
Te ir pāris lietas:
1. Ja pirmajā IF tiek mests exception, tad pārējo var nelikt else if/else blokos, jo ja pirmais IF izpildās, tad ir kļūda un nekas tālāk neizpildās.
2. Uzdevumā tā doma īsti nebija, ja nauda ir zem 100, tad nevar izņemt, bet tā šobrīd faktiski ir uzrakstīts
Tāpēc metode var izskatīties šādi:
```
       if (moneyAmount > getBalance()) {
            throw new NotEnoughFundsException("Insufficient funds");
        } 
        setBalance(getBalance() - moneyAmount);
        if (getBalance() < 100) {
            displayMessage();
        } 
```
Tajā brīdī var arī uzreiz pamanīt, ka faktiski pirmā puse sakrīt ar DebitCard takeMoney metodi
Tāpēc kopīgo daļu var pārnest uz Card klasi, tā ka šeit paliek tikai:
```
       super.takeMoney(moneyAmount);
        if (getBalance() < 100) {
            displayMessage();
        } 
```

2022-04-02 10:03 UTC, janistumpelis commented on src/main/java/io/codelex/javaadvancedtest/exercise2/Basket.java
> +    private T items;
Šim drīzāk būtu jābūt List<T>, tā lai tās lietas tiešām var pievienot grozam, bet šobrīd sanāk, ka skaits tiek palielināts, bet faktiski grozam nekas klāt netiek likts.

2022-04-02 10:03 UTC, janistumpelis commented on src/main/java/io/codelex/javaadvancedtest/exercise2/Basket.java
> +    public void addToBasket() throws BasketFullException {
addToBasket metodei ir jāsaņem parametrs ar lietu, kuru vēlies pievienot grozam:
`public void addToBasket(T item) ..`

2022-04-02 13:38 UTC, GitaVazdike commented on src/main/java/io/codelex/javaadvancedtest/exercise1/CreditCard.java
> +    public void takeMoney(double moneyAmount) throws NotEnoughFundsException {
Lūk!!! Šis ir tas, kas man vakar maisījās galvā, bet ārā tā arī neiznāca - "super" keywords! Tagad ieraugot, liekas pašsaprotami, bet vakar nevarēju atcerēties. Laikam bija prāta aptumsums.... Paldies! :)

2022-04-03 21:08 UTC, GitaVazdike commented
Paldies par komentāriem. Izlaboju.
Pagāja krietni vairāk par trim stundām, bet uzdevumiem izburties cauri izdevās. Par piekto gan jāatzīst, ja Tu nebūtu testa beigās parādījis, kā to atrisināt, nez vai pati būtu tikusi galā.

2022-04-03 21:13 UTC, GitaVazdike commented on src/main/java/io/codelex/javaadvancedtest/exercise1/CreditCard.java
> +    public void takeMoney(double moneyAmount) throws NotEnoughFundsException {
Izlabots.

2022-04-03 21:13 UTC, GitaVazdike commented on src/main/java/io/codelex/javaadvancedtest/exercise1/Card.java
> +    private double balance;
Izlabots.

2022-04-03 21:13 UTC, GitaVazdike commented on src/main/java/io/codelex/javaadvancedtest/exercise2/Basket.java
> +    private T items;
Izlabots.

2022-04-03 21:13 UTC, GitaVazdike commented on src/main/java/io/codelex/javaadvancedtest/exercise2/Basket.java
> +    public void addToBasket() throws BasketFullException {
Izlabots.

2022-05-01 12:30 UTC, janistumpelis approved these changes

2022-05-02 16:15 UTC, merged