Finished Exercises: Flowcontrol and Loops.
GitaVazdike/codelex-exercises pull request #2
Opened 2022-03-01 00:01 UTC by GitaVazdike

2022-03-06 17:50 UTC, NilsKula requested changes

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +                } else if (n >= 100 && n < 1000) {
nav nepieciešams pārbaudīt `n>=100`, ja būs zem 100 tad viņš trapīs jau iepriekšējā if un līdz šejienei nemaz netiks

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/flowcontrol/exercises/Exercise4.java
> +    public static void PrintDayInWord(int dayNumber) {
metodes camelCase vienmēr `printDayInWord` un metode var būt arī private šeit

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Exercise5.java
> +        for (int i = wordLengthSum; i < 30; i++) {
30 arī labāk varētu apzīmēt ar mainīgo

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/Piglet.java
> +                int rolledNumber = (int) (Math.random() * 6) + 1;
Šeit labak izmantot Random.nextInt(), casting labāk censties izlaist pēc iespējas

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/AsciiFigure.java
> +    public static final int size = 7;
var būt private

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/AsciiFigure.java
> +        int figureLength = size * 8 - 8;
8 arī varētu par kaut ko nodēvēt

2022-03-06 17:50 UTC, NilsKula commented on src/main/java/io/codelex/loops/exercises/RollTwoDice.java
> +                randomNumber1 = random1.nextInt((max - min) + 1) + min;
šo jau arī potenciāli varētu izvilkt uz palīgmetodi, jo atkārtojas

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +                } else if (n >= 100 && n < 1000) {
Izlabots.

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/flowcontrol/exercises/Exercise4.java
> +    public static void PrintDayInWord(int dayNumber) {
Izlabots.

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/loops/exercises/Exercise5.java
> +        for (int i = wordLengthSum; i < 30; i++) {
Izlabots.

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/loops/exercises/Piglet.java
> +                int rolledNumber = (int) (Math.random() * 6) + 1;
Izlabots.

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/loops/exercises/AsciiFigure.java
> +    public static final int size = 7;
Izlabots.

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/loops/exercises/AsciiFigure.java
> +        int figureLength = size * 8 - 8;
Izlabots.

2022-03-10 10:46 UTC, GitaVazdike commented on src/main/java/io/codelex/loops/exercises/RollTwoDice.java
> +                randomNumber1 = random1.nextInt((max - min) + 1) + min;
Izlabots.

2022-03-10 11:45 UTC, NilsKula approved these changes

2022-03-10 17:40 UTC, merged