Exercises collections
GitaVazdike/codelex-exercises pull request #9
Opened 2022-03-25 20:45 UTC by GitaVazdike

2022-04-10 12:33 UTC, NilsKula requested changes

2022-04-10 12:33 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
>      String name;
private

2022-04-10 12:33 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Exercise5.java
> +        return number == 1;
labak vien papildus variabli, savadāk nedaud zdīvaini lasīt, ka padod number un beidzas ar `return number == 1`

2022-04-10 12:33 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +    private static List<String[]> listOfStartCitiesAndDestinations = new ArrayList<>();
final and caps

2022-04-10 12:33 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +            if (!userInput.equals("1") && !userInput.equals("#")) {
`if(isValidInput())`

2022-04-10 12:33 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +        int lessThanTenCount = listOfScores.stream().filter((Integer number) -> number < 10).toList().size();
šķiet ka šo varētu noteikti saīsināt ar loop

2022-04-11 21:27 UTC, GitaVazdike commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +        int lessThanTenCount = listOfScores.stream().filter((Integer number) -> number < 10).toList().size();
Es pareizi saprotu - likt loop un if-us? Tad man kods sašaurinās, bet pamatīgi pagarinās uz leju. :)
Vai arī es neuztvēru domu?

2022-04-13 12:20 UTC, GitaVazdike commented on src/main/java/io/codelex/collections/practice/Histogram.java
> +        int lessThanTenCount = listOfScores.stream().filter((Integer number) -> number < 10).toList().size();
Ieliku loopu. Neko īsāku nevaru iedomāties.

2022-04-13 12:20 UTC, GitaVazdike commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +            if (!userInput.equals("1") && !userInput.equals("#")) {
Izlabots.

2022-04-13 12:20 UTC, GitaVazdike commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +    private static List<String[]> listOfStartCitiesAndDestinations = new ArrayList<>();
Izlabots.

2022-04-13 12:20 UTC, GitaVazdike commented on src/main/java/io/codelex/collections/practice/Exercise5.java
> +        return number == 1;
Izlabots.

2022-04-13 12:20 UTC, GitaVazdike commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneEntry.java
>      String name;
Izlabots.

2022-04-15 17:54 UTC, NilsKula approved these changes

2022-04-19 08:30 UTC, merged